### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by MartinSarkany** [lastfreenickname/GIFparser#3]
Description: not releasing buffer of size up to 4294836225 bytes (4.3 GB)
Severity: high
Risk: high
Remediation: compare to actual size of file & free the memory
Location: GIFparser.cpp:381 - 393

**Comment by lastfreenickname** [comment]
As for comparing to actual size of file - hard to do, here we allocate array for uncompressed image data, and the array size is taken from uncompressed image dimensions declared in the data block header (which is the only available information about the uncompressed block size). If after decompression the actual length of decompressed data is not the expected one, program ends with error.
