### ISSUE TITLE
Application crash

### ISSUE THREAD

**Issue by MartinSarkany** [lastfreenickname/GIFparser#5]
Description: Buffer overrun on stack in lzw_uncompress_data_block()
Severity: medium
Risk: medium
Remediation: Kill that function with fire!
Location: Somewhere in lzw_uncompress_data_block(), good luck finding it

**Comment by lastfreenickname** [comment]
I intended to kill the function with fire, unfortunately I haven't found any suitable library function to replace it with. Instead, I added checks on buffer indices to catch when they run out of bounds. Please feel free to retest with the input file that caused the issue and reopen it if necessary:)

**Comment by MartinSarkany** [comment]
![1](https://cloud.githubusercontent.com/assets/18403585/21957555/ea56587e-da98-11e6-8a88-98695d0cbeaa.gif)
Try this one. 
(Also consider including string.h - memset() and memcmp() functions - but that doesn't belong to this issue.)

**Comment by lastfreenickname** [comment]
Thanks, that helped to fix the issue properly (and check the boundaries before writing to the array and not after).
Parser no longer crashes on this input.
